# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main
  
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'dockerhub-connection'
    #     repository: 'pdemeulenaer/mlflow-server'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          ls
          cat $(Build.SourcesDirectory)/Dockerfile

    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift_connect'
        cmd: 'oc get deploy'
        uselocalOc: true
      displayName: 'Connect to Openshift'

      
      
    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     #cmd: 'oc new-build --name rf-sklearn-image --strategy=docker https://github.com/pdemeulenaer/mlflow-rf-sklearn.git '
    #     cmd: 'oc new-app $(Build.SourcesDirectory)/production --strategy=docker | oc expose service/mlflow-rf-sklearn'
    #     uselocalOc: true
    #   displayName: 'Deploy using docker strategy' 

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc new-app image-registry.openshift-image-registry.svc:5000/pdemeulenaer-dev/mlflow-rf-sklearn:latest'
    #     uselocalOc: true
    #   displayName: 'Deploy using docker strategy' 

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc new-app --name mlflow-rf-sklearn $(Build.SourcesDirectory) --strategy=docker | oc expose service/mlflow-rf-sklearn'
    #     uselocalOc: true
    #   displayName: 'Deploy using docker strategy' 



    # # DEPLOYING iris-data-generation
    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete deployment iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Deleting previous deployment' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete bc iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Deleting previous buildconfig' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete svc iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Deleting previous service' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete route iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Deleting previous route' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc new-app https://github.com/pdemeulenaer/mlflow-rf-sklearn.git --context-dir=data_generation --name=iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Deploy using direct build strategy' 

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc expose service/iris-data-generation'
    #     uselocalOc: true
    #   displayName: 'Exposing the route for iris-data-generation' 

    # # DEPLOYING iris-rf-prediction
    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete deployment iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous deployment' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete bc iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous buildconfig' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete svc iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous service' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete route iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous route' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc new-app https://github.com/pdemeulenaer/mlflow-rf-sklearn.git --context-dir=prediction --name=iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Deploy using direct build strategy' 

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc expose service/iris-rf-prediction'
    #     uselocalOc: true
    #   displayName: 'Exposing the route'     
      
    # # DEPLOYING iris-show-prediction
    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete deployment iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous deployment' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete bc iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous buildconfig' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete svc iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous service' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc delete route iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Deleting previous route' 
    #   continueOnError: true

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc new-app https://github.com/pdemeulenaer/mlflow-rf-sklearn.git --context-dir=request_app --name=iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Deploy using direct build strategy' 

    # - task: oc-cmd@2
    #   inputs:
    #     connectionType: 'OpenShift Connection Service'
    #     openshiftService: 'openshift_connect'
    #     cmd: 'oc expose service/iris-show-prediction'
    #     uselocalOc: true
    #   displayName: 'Exposing the route'      